### PR TITLE
Major rewrite

### PR DESCRIPTION
**Pull request by Jibec**
hi, here are more significant changes, to review after the other pull request.
work is still in progress and is an invitation to discuss together, not fully tested.

As of now, it doesn't work on my VM Debian 9 / YunoHost 3. But it has exactly the same behavior as your code: it does install but I can't connect.

Please do not merge before we both confirm it is working fine :)

### CODE REVIEW

**Comment by alexAubin** [comment]
(bump @src386 ? In case you don't want to maintain this app anymore, it can be maintained on behalf of YunoHost-Apps if there are people like @Jibec to volunteer)

**Comment by alexAubin** [comment]
Would be nice to know what to do with this, also considering  that the app is now flagged as unmaintained ...

If this PR really does improve stuff it'd be nice to merge it :/ 

Could run this branch on the dev CI to see if there's no regression ...

**Comment by Jibec** [comment]
indeed, it's been a long time now... can you please give set me as a maintainer @alexAubin ? It will take some days/weeks/months, but I'll finish this package and get people onboard.

**Comment by alexAubin** [comment]
I don't have write access to this repo :/ But maybe we could simply fork it to @Yunohost-Apps ?

**Comment by maniackcrudelis** [comment]
This app is no longer maintained, https://github.com/movim/movim_ynh/issues/51.
We do not have write permission on this repo.

Therefor, please redirect your PR to the fork in YunoHost-Apps, https://github.com/yunohost-apps/movim_ynh.

**Comment by Jibec** [comment]
ij

**Pull request closed without merging**
