### PR TITLE
Update package for YunoHost 2.4 and download source code

### PR DESCRIPTION
**Pull request by jeromelebleu**
This PR changes the following:
 * download and update source code using git - it meanly allows one to trust easier the source code integrity, ease the new version update and make lighter the repository
 * make use of new YunoHost helpers coming with the 2.4 version
 * add `backup` and `restore` scripts
 * redirect to the SSO on logging out
 * be less verbose with some commands - i.e. composer and `systemctl`

### CODE REVIEW

**Comment by src386** [comment]
Hi, thanks, let me take a look at this before I merge.
backup and restore are useless because movim data are stored in metronome.
mysql is only for cache.

**Comment by src386** [comment]
This pull request makes movim_ynh depend on Yunohost 2.4.
Yunohost 2.4 is available only for Debian Jessie, is it relevant to keep sysvinit scripts ?

**Comment by src386** [comment]
Not sure if it's a good idea to drop YunoHost-2.2 support, it's too early.

**Comment by src386** [comment]
Thanks again, @jeromelebleu . Your code is really clean, that's a huge improvement for movim_ynh.

> download and update source code using git - it meanly allows one to trust easier the source code integrity, ease the new version update and make lighter the repository

merged.

> make use of new YunoHost helpers coming with the 2.4 version

I wanted to keep yh2.2 compatibility, so I had to backport the helpers and edit manifest.json (boolean and ynh version requirement). If /usr/share/yunohost/helpers does not exists, they are loaded from ./_helpers.

> add backup and restore scripts

Removed since they doesn't work and are not easy to test (not to say it's a real pain in yunohost). Anyway Movim doesn't store critical data, it's just cache.

> redirect to the SSO on logging out

merged

> be less verbose with some commands - i.e. composer and systemctl

removed because I want verbose output.

**Comment by jeromelebleu** [comment]
With pleasure!

> Yunohost 2.4 is available only for Debian Jessie, is it relevant to keep sysvinit scripts ?

You're right, it's useless in that case.

> Not sure if it's a good idea to drop YunoHost-2.2 support, it's too early.

I can just highly recommend to upgrade to YunoHost 2.4... There is no more updates and fixes since ~1 year on the 2.2 version. Moreover, this new version bring a lot of new features - especially for app packaging.

>>  add backup and restore scripts
>
> Removed since they doesn't work and are not easy to test (not to say it's a real pain in yunohost).

We should document that, sorry. They were working in my PR, but I think [this line](https://github.com/movim/movim_ynh/commit/96bce7d455b470bd90f65bb934d219cbbb371a98#diff-dab29616182e947d2761d52c308b0d60R11) broke it since `backup` and `restore` scripts are not - yet - executed in the same folder than the app package - as it is for the other scripts.
Anyway, to test it - and only this app backup, you can execute the following:

```bash
# create a backup of movim app only named movim-backup
yunohost backup create --ignore-hooks --apps movim --name movim-backup --verbose
# delete the current app - otherwise restoration will not be possible
yunohost backup restore movim-backup --verbose
```

> Anyway Movim doesn't store critical data, it's just cache.

I think that it's always useful to have those scripts to easily restore a system ~ at a previous state, but I let you decide...

**Comment by src386** [comment]
I didn't know it was possible to backup & restore a single app, it makes things easier.
I'll take a look, Thanks.

**Comment by jeromelebleu** [comment]
You're welcome! And by the way, thanks a lot for this package!

**Comment by jeromelebleu** [comment]
I've forgot to argue on one point...

>> be less verbose with some commands - i.e. composer and systemctl
>
> removed because I want verbose output.

The fact is that `git`, `systemctl` and `composer` use *stderr* even for non-error messages. It results in a lot of `Warning: ...` from YunoHost side... One possibility if you want to keep verbose output can be to redirect *stderr* to *stdout*, but we will then not distinguish errors from information.

**Pull request merged**
